application/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'application'
log_url = 'application:login'
urlpatterns = [
    # -------------------------------------------------------------------------------------------
    #               GENERAL URLS
    # -------------------------------------------------------------------------------------------
    path('', views.IndexView.as_view(), name='index'),
    path('index/', views.IndexView.as_view(), name='index1'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('test/', views.TestView.as_view(), name='test'),

    # -------------------------------------------------------------------------------------------
    #               TEACHER URLS
    # -------------------------------------------------------------------------------------------
    url(r'^teacher/course/(?P<course_id>[0-9]+)/$',
        login_required(views.TeacherCourseDetailView.as_view(), login_url=log_url),
        name='teacherCourseViewWithcourse_id'),
    path('teacher/', login_required(views.TeacherView.as_view(), login_url=log_url), name='teacher'),
    path('teacher/course/<int:course_id>/addtopic', views.content_form, name='contentForm'),
    path('teacher/appointments/', views.AppointmentView.as_view(), name='appointment'),  # NOT USED! Don't Touch!
    path('teacher/appointments/<int:teacher_id>/', views.appointment_form, name='appointmentWithID'),
    path('teacher/timetables/', views.TimetablesView.as_view(), name='timetables'),  # NOT USED! Don't Touch!
    path('teacher/timetables/<int:teacher_id>/', views.TimetablesWithIDView.as_view(), name='timetablesWithID'),
    path('teacher/timetables/<int:teacher_id>/<int:class_id>/', views.timetables_specific_class_view, name='timetablesWithIDSpecificClass'),
    url(r'^teacher/course/(?P<course_id>[0-9]+)/addPerformanceGrade/$', views.grade_form, name='gradeForm'),
    path('teacher/course/<int:course_id>/addAssignment', views.assignment_form, name='assignmentForm'),
    url(r'^teacher/course/(?P<course_id>[0-9]+)/absence/$', views.absence_form, name='absenceForm'),
    url(r'^teacher/course/(?P<course_id>[0-9]+)/behavior/$', views.behavior_form, name='behaviorForm'),
    path('teacher/coordinatedClass', views.TeacherClassCoordinated.as_view(), name='TeacherCoordinator'),
    url(r'^teacher/coordinatedClass/studentCourses/(?P<student_id>[0-9]+)/$',
        login_required(views.final_grade_form, login_url=log_url),
        name='putFinalGrade'),
    # -------------------------------------------------------------------------------------------
    #               PARENT URLS
    # -------------------------------------------------------------------------------------------
    path('parent/', views.parent_view, name='parent'),
    url(r'^parent/(?P<student_id>[0-9]+)/$', views.parent_view, name='parentWithID'),
    url(r'^parent/grades/(?P<student_id>[0-9]+)/$',
        login_required(views.ParentGradeView.as_view(), login_url=log_url), name='parentGradeWithID'),
    path('parent/grades/', login_required(views.ParentGradeView.as_view(), login_url=log_url),
         name='parentGrade'),
    path('chooseChild/', login_required(views.ChooseChild.as_view(), login_url=log_url),
         name='chooseChild'),
    path('parent/attendance', login_required(views.ParentAttendanceView.as_view(), login_url=log_url),
         name='parentAttendance'),
    path('parent/behavior', login_required(views.ParentBehaviorView.as_view(), login_url=log_url),
         name='parentBehavior'),
    url(r'^parent/(?P<student_id>[0-9]+)/course/$',
        login_required(views.CourseView.as_view(), login_url=log_url), name='courseView'),
    # NOT HANDLED URL PLEASE DONT USE
    url(r'^parent/(?P<student_id>[0-9]+)/course/(?P<course_id>[0-9]+)/$',
        login_required(views.CourseDetailView.as_view(), login_url=log_url),
        name='courseViewWithcourse_id'),
    path('change-password/', views.change_password, name='change_password'),
    url(r'^parent/(?P<student_id>[0-9]+)/course/(?P<course_id>[0-9]+)/assignments/$',
        login_required(views.AssignmentView.as_view(), login_url=log_url), name='assignments'),
    url(r'^parent/(?P<student_id>[0-9]+)/course/(?P<course_id>[0-9]+)/materials/$',
        login_required(views.MaterialView.as_view(), login_url=log_url), name='materials'),
    url(r'^parent/(?P<student_id>[0-9]+)/course/(?P<course_id>[0-9]+)/attendance/$',
        login_required(views.ParentAttendanceView.as_view(), login_url=log_url), name='parentAttendance'),
    url(r'^parent/(?P<student_id>[0-9]+)/course/(?P<course_id>[0-9]+)/behavior/$',
        login_required(views.ParentBehaviorView.as_view(), login_url=log_url), name='parentBehavior'),
    path('parent/<int:student_id>/announcement/', views.AnnouncementView.as_view(), name='announcement'),
    path('parent/<int:student_id>/course/<int:course_id>/notes/', views.NotesView.as_view(), name='CourseNote'),
    path('parent/<int:student_id>/finalResult/', views.FinalGradeView.as_view(), name='finalResult'),

    # -------------------------------------------------------------------------------------------
    #               ADMINISTRATIVE OFFICER URLS
    # -------------------------------------------------------------------------------------------
    path('signup/', views.enroll_student, name='signup'),  # student signup
    path('ao/', login_required(views.AdministrativeOfficer.as_view(), login_url='application:login'), name='ao'),
    url(r'^ao/class/(?P<name>[0-9][A-Z]+)/$', views.timetable_form, name='timetableForm'),
    path('communicationAO/', views.communication_ao, name='communicationAO'),
    path('aoConstraint/', views.constraints_form, name='constraintAOForm'),
    path('teacherMasterData/', views.GetTeacherMasterData.as_view(), name='teacherMasterData'),
    path('parentsignup/', views.parent_signup, name='parentSignup'),
    path('composeClass/', views.class_compose, name='classCompose'),
    path('teacheredit/<pk>/', views.EditTeacherMasterData.as_view(), name='teacher-edit'),
    path('teacherMasterData/<pk>', views.GetTeacherMasterData.as_view(), name='teacherMasterData'),
    path('teacheradd/', views.teacher_create, name='teacher-add'),
    url(r'teacher/(?P<pk>[0 -9]+)/delete/$', views.DeleteTeacherMasterData.as_view(), name='teacher-delete'),

    # -------------------------------------------------------------------------------------------
    #               STUDENT URLS
    # -------------------------------------------------------------------------------------------
    path('student/<int:student_id>', views.student_login_view, name='student_login_view'),
    path('student/<int:student_id>/assignments', views.student_assignment_view, name='student_assignment')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newSchoolWebsite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('application/', include('application.urls')),
    path('', RedirectView.as_view(url='application/index/', permanent=True)),
]
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

application/views.py
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.contrib.auth.views import redirect_to_login
from django.db.models import Sum
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import UpdateView, DeleteView
from django.db.models import Q
import csv
from functools import partial, wraps
from django.forms import formset_factory
from .models import StudentCourse, PerformanceGrade, Parent, Content, Course, Student, ClassInfo, TeacherCourse, \
    ParentStudent, Attendance, Assignment, Announcement, Teacher, Note, Behavior, ClassCourse, Adminofficerconstraint
from django.views import generic
from application.forms import StudentForm, ParentSignUpForm, ClassComposeForm, ContentForm, PerformanceGradeForm, \
    AbsenceForm, AssignmentForm, TimetableForm, AnnouncementForm, TeacherCreateForm, AppointmentsForm, \
    PutFinalGradeForm, BehaviorForm, AdminofficerconstraintForm
from django.core.exceptions import ValidationError


# -----------------------------------------------------------------------------------------------
####### HELPER FUNCTIONS AREA##########
# -----------------------------------------------------------------------------------------------
ao_app = 'application:ao'
adm_off = 'administrativeOfficer/enrollStudent.html'


def read_csv_file(file, dictionary, used_delimiter):
    csv_file = open(file.path, 'r')
    read_csv = csv.reader(csv_file, delimiter=used_delimiter)
    first = 1
    index = 0
    for row in read_csv:
        if first == 1:
            first = 0
            dictionary.update({'header0': row[0]})
            dictionary.update({'header1': row[1]})
            dictionary.update({'header2': row[2]})
            dictionary.update({'header3': row[3]})
            dictionary.update({'header4': row[4]})
            dictionary.update({'header5': row[5]})
        else:
            dictionary.update({'row' + str(index) + '0': row[0]})
            dictionary.update({'row' + str(index) + '1': row[1]})
            dictionary.update({'row' + str(index) + '2': row[2]})
            dictionary.update({'row' + str(index) + '3': row[3]})
            dictionary.update({'row' + str(index) + '4': row[4]})
            dictionary.update({'row' + str(index) + '5': row[5]})
            index += 1


def number_of_seats():
    number = ClassInfo.objects.aggregate((Sum('totalStudentsNumber')))['totalStudentsNumber__sum']
    return number


def number_of_students():
    number = Student.objects.filter(classID=None).count()
    return number


class RequireLoginMixin:
    def dispatch(self,request,*args,**kwargs):
        if not request.user.is_authenticated():
            return  redirect_to_login(request.get_full_path())
        return super(RequireLoginMixin,self).dispatch(request,*args,**kwargs)


# -----------------------------------------------------------------------------------------------
####### ADMINISTRATIVE OFFICER AREA##########
# -----------------------------------------------------------------------------------------------
class AdministrativeOfficer(generic.ListView):
    template_name = 'administrativeOfficer/aoAfterLogin.html'
    context_object_name = 'allClasses'

    def get_queryset(self):
        return ClassInfo.objects.all()


@login_required(login_url='application:login')
def timetable_form(request, name):
    if request.method == 'POST':
        instance = ClassInfo.objects.get(name=name)
        form = TimetableForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(ao_app)
    else:
        form = TimetableForm()

    my_dict = {'class': ClassInfo.objects.filter(name=name)}  # GET CLASS NAME
    if ClassInfo.objects.filter(name=name).exists():
        my_dict.update({'class': ClassInfo.objects.get(name=name)})
    my_dict.update({'name': name})
    timetable = my_dict['class'].timetable
    try:
        read_csv_file(file=timetable, dictionary=my_dict, used_delimiter=',')
        my_dict.update({'class': 'timetable'})
    except:
        pass
    return render(request, 'administrativeOfficer/chooseTimetable.html',
                  {'form': form, 'name': name, 'my_dict': my_dict, 'class': ClassInfo.objects.get(name=name)})


@login_required(login_url='application:login')
def enroll_student(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = StudentForm(request.POST)
        try:
            user = User.objects.get(username=request.POST['username'], )
            return render(request, adm_off,
                          {'error_message': 'Username already Exist.\nTry another Username.', 'form': StudentForm()})
        except User.DoesNotExist:
            if form.is_valid():
                user = form.save()
                user.refresh_from_db()  # load the profile instance created by the signal
                student = Student.objects.create(user=user, studentYear=form['student_year'].value())
            messages.success(request, 'Student has been successfully added')
            return render(request, adm_off, {'form': StudentForm()})
            # if a GET (or any other method) we'll create a blank form
    else:
        form = StudentForm()
    return render(request, adm_off, {'form': form})


@login_required(login_url='application:login')
def parent_signup(request):
    if request.method == 'POST':
        form = ParentSignUpForm(request.POST)
        try:
            user = User.objects.get(username=request.POST['username'], )
            return render(request, 'administrativeOfficer/parentSignup.html',
                          {'error_message': 'Username Exist...Try Something Else !', 'form': ParentSignUpForm()})
        except User.DoesNotExist:
            if form.is_valid():
                user = form.save()
                user.refresh_from_db()  # load the profile instance created by the signal
                parent = Parent.objects.create(user=user, )
                for student in form.cleaned_data.get('student_id'):
                    ParentStudent.objects.create(student_id=student, parentID=parent)

                messages.success(request, 'Parent has been successfully added')

                username = request.POST['username']
                email = request.POST['email']
                password = request.POST['password2']
                send_mail_to_parent(username, email, password)  # send credentials to a parent

                return render(request, 'administrativeOfficer/parentSignup.html', {'form': ParentSignUpForm()})
            else:
                return render(request, 'administrativeOfficer/parentSignup.html',
                              {'error_message': 'Invalid Information', 'form': ParentSignUpForm()})
    else:
        form = ParentSignUpForm()
    return render(request, 'administrativeOfficer/parentSignup.html', {'form': form})


@login_required(login_url='application:login')
def class_compose(request):
    if request.method == 'POST':
        form = ClassComposeForm(request.POST)
        if form.is_valid():
            class_info = form.save()
            class_info.refresh_from_db()
            if class_info.name[0] == '1':
                course1 = Course.objects.get_or_create(name='Math', numberOfHoursPerWeek='10', year='FIRST')
                course2 = Course.objects.get_or_create(name='Physics', numberOfHoursPerWeek='10', year='FIRST')
                course3 = Course.objects.get_or_create(name='English', numberOfHoursPerWeek='10', year='FIRST')
                course4 = Course.objects.get_or_create(name='Italian', numberOfHoursPerWeek='10', year='FIRST')
                course5 = Course.objects.get_or_create(name='Latin', numberOfHoursPerWeek='10', year='FIRST')
                course6 = Course.objects.get_or_create(name='Art', numberOfHoursPerWeek='10', year='FIRST')
                course7 = Course.objects.get_or_create(name='Gym', numberOfHoursPerWeek='10', year='FIRST')
                course8 = Course.objects.get_or_create(name='Spanish', numberOfHoursPerWeek='10', year='FIRST')

                ClassCourse.objects.get_or_create(class_id=class_info, course_id=course1[0],
                                                  teacher_id=Teacher.objects.get(first_name='Marco'))
                ClassCourse.objects.get_or_create(class_id=class_info, course_id=course2[0],
                                                  teacher_id=Teacher.objects.get(first_name='Marco'))
                ClassCourse.objects.get_or_create(class_id=class_info, course_id=course3[0],
                                                  teacher_id=Teacher.objects.get(first_name='Marco'))
                ClassCourse.objects.get_or_create(class_id=class_info, course_id=course4[0],
                                                  teacher_id=Teacher.objects.get(first_name='Marco'))
                ClassCourse.objects.get_or_create(class_id=class_info, course_id=course5[0],
                                                  teacher_id=Teacher.objects.get(first_name='Antonio'))
                ClassCourse.objects.get_or_create(class_id=class_info, course_id=course6[0],
                                                  teacher_id=Teacher.objects.get(first_name='Antonio'))

                ClassCourse.objects.get_or_create(class_id=class_info, course_id=course7[0],
                                                  teacher_id=Teacher.objects.get(first_name='Antonio'))
                ClassCourse.objects.get_or_create(class_id=class_info, course_id=course8[0],

application/templates/parent/afterloginparent.html
{% extends 'parent/base.html' %}
{% block body %}
    <h1 style="padding-left: 2%">Welcome {{ user.first_name }}<br></h1>
    <h3 style="padding-left: 2%">Your child:{% for p in parentStudent %} {{ p.student_id }} {% endfor %}
        <br>Class: {{ studentClass }} </h3>

    <div style="padding-left: 2%">
        <h2> Student Courses</h2>
        <ul>
            {% for studentcourse in allStudentCourses %}
                <li style="padding-bottom: 1%"><a
                        href="{% url 'application:courseView' student_id %}{{ studentcourse.ID }}"
                        class="btn btn-primary btn-lg" style="font-size: 20px"> {{ studentcourse.name }} </a></li>
            {% endfor %}
        </ul>

    </div>
    <br><br>
    <div style="padding-left: 2%">
        <h2>Time Table</h2>
        {% if timeTable %}
            <table>
                <th>{{ header0 }}</th>
                <th>{{ header1 }}</th>
                <th>{{ header2 }}</th>
                <th>{{ header3 }}</th>
                <th>{{ header4 }}</th>
                <th>{{ header5 }}</th>
                <tr>
                    <td>{{ row00 }}</td>
                    <td>{{ row01 }}</td>
                    <td>{{ row02 }}</td>
                    <td>{{ row03 }}</td>
                    <td>{{ row04 }}</td>
                    <td>{{ row05 }}</td>
                </tr>
                <tr>
                    <td>{{ row10 }}</td>
                    <td>{{ row11 }}</td>
                    <td>{{ row12 }}</td>
                    <td>{{ row13 }}</td>
                    <td>{{ row14 }}</td>
                    <td>{{ row15 }}</td>
                </tr>
                <tr>
                    <td>{{ row20 }}</td>
                    <td>{{ row21 }}</td>
                    <td>{{ row22 }}</td>
                    <td>{{ row23 }}</td>
                    <td>{{ row24 }}</td>
                    <td>{{ row25 }}</td>
                </tr>
                <tr>
                    <td>{{ row30 }}</td>
                    <td>{{ row31 }}</td>
                    <td>{{ row32 }}</td>
                    <td>{{ row33 }}</td>
                    <td>{{ row34 }}</td>
                    <td>{{ row35 }}</td>
                </tr>
                <tr>
                    <td>{{ row40 }}</td>
                    <td>{{ row41 }}</td>
                    <td>{{ row42 }}</td>
                    <td>{{ row43 }}</td>
                    <td>{{ row44 }}</td>
                    <td>{{ row45 }}</td>
                </tr>
                <tr>
                    <td>{{ row50 }}</td>
                    <td>{{ row51 }}</td>
                    <td>{{ row52 }}</td>
                    <td>{{ row53 }}</td>
                    <td>{{ row54 }}</td>
                    <td>{{ row55 }}</td>
                </tr>
            </table>
        {% else %}
            <ul>
                <li>
                    Time table is not uploaded yet
                </li>
            </ul>
        {% endif %}
    </div>


{% endblock %}

application/templates/parent/assignmentBase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Kiddos - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fredericka+the+Great" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="../../../../../../static/application/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="../../../../../../static/application/css/animate.css">
    <link rel="stylesheet" href="../../../../../../static/application/css/owl.carousel.min.css">
    <link rel="stylesheet" href="../../../../../../static/application/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="../../../../../../static/application/css/magnific-popup.css">
    <link rel="stylesheet" href="../../../../../../static/application/css/aos.css">
    <link rel="stylesheet" href="../../../../../../static/application/css/ionicons.min.css">
    <link rel="stylesheet" href="../../../../../../static/application/css/flaticon.css">
    <link rel="stylesheet" href="../../../../../../static/application/css/icomoon.css">
    <link rel="stylesheet" href="../../../../../../static/application/css/style.css">
</head>
<body>
<div class="py-2 bg-primary">
    <div class="container">
        <div class="row no-gutters d-flex align-items-start align-items-center px-3 px-md-0 pull-right">
            <div class="col-lg-12 d-block">
                <div class="row d-flex">
                    <div class="col-md pr-4 d-flex topper align-items-right">
                        <div class="icon bg-tertiary mr-2 d-flex justify-content-center align-items-center"><span
                                class="glyphicon glyphicon-user"></span></div>
                        <a class="btn btn-outline-primary" href="{% url 'application:logout' %}" role="button"><span
                                class="text">Logout</span></a>  <!--ADD LOGOUT HERE-->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<nav class="navbar navbar-expand-lg navbar-light bg-light ftco_navbar ftco-navbar-light" id="ftco-navbar">
    <div class="container d-flex align-items-center">
        <a class="navbar-brand" href="{% url 'application:parentWithID' student_id %}" style="font-size: 30px">Kiddos</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav" style="font-size: 14px">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{% url 'application:parentWithID' student_id %}"
                                               class="nav-link pl-0">Home</a></li>
                <li class="nav-item"><a href="{% url 'application:parentAttendance' student_id course_id %}"
                                        class="nav-link pl-0">Attendance</a></li>
                <li class="nav-item"><a href="{% url 'application:materials' student_id course_id %}"
                                        class="nav-link pl-0">Materials</a></li>
                <li class="nav-item"><a href="{% url 'application:assignments' student_id course_id %}"
                                        class="nav-link pl-0">Assignments</a></li>
                <li class="nav-item"><a href="{% url 'application:CourseNote' student_id course_id %}"
                                        class="nav-link pl-0">Notes</a></li>
                <li class="nav-item"><a href="{% url 'application:parentBehavior' student_id course_id %}"
                                        class="nav-link pl-0">Behavior</a></li>
            </ul>
        </div>
    </div>
</nav>
<!-- END nav -->

{% block body %}

{% endblock %}


<br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<footer class="ftco-footer ftco-bg-dark ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-6 col-lg-3">
                <div class="ftco-footer-widget mb-5">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                    class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-lg-3">
                <div class="ftco-footer-widget mb-5 ml-md-4">
                    <h2 class="ftco-heading-2">Links</h2>
                    <ul class="list-unstyled">
                        <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>Home</a></li>
                        <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>About</a></li>
                        <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>Teachers</a></li>
                        <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>Courses</a></li>
                        <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>Contact</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="ftco-footer-widget mb-5">
                    <h2 class="ftco-heading-2 mb-0">Connect With Us</h2>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                    All rights reserved <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com"
                                                                                            target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
            </div>
        </div>
    </div>
</footer>


<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>


<script src="../../../../../../static/application/js/jquery.min.js"></script>
<script src="../../../../../../static/application/js/jquery-migrate-3.0.1.min.js"></script>
<script src="../../../../../../static/application/js/popper.min.js"></script>
<script src="../../../../../../static/application/js/bootstrap.min.js"></script>
<script src="../../../../../../static/application/js/jquery.easing.1.3.js"></script>
<script src="../../../../../../static/application/js/jquery.waypoints.min.js"></script>
<script src="../../../../../../static/application/js/jquery.stellar.min.js"></script>
<script src="../../../../../../static/application/js/owl.carousel.min.js"></script>
<script src="../../../../../../static/application/js/jquery.magnific-popup.min.js"></script>
<script src="../../../../../../static/application/js/aos.js"></script>
<script src="../../../../../../static/application/js/jquery.animateNumber.min.js"></script>
<script src="../../../../../../static/application/js/scrollax.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="../../../../../../static/application/js/google-map.js"></script>
<script src="../../../../../../static/application/js/main.js"></script>

</body>
</html>